import type { Metadata } from 'next';
// import { Inter } from 'next/font/google'
import { Figtree } from 'next/font/google';

import './globals.css';

const figtree = Figtree({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={figtree.className}>{children}</body>
    </html>
  );
}
